scss_files: 'source/stylesheets/**/*.scss'
exclude: 'source/stylesheets/*.css'
linters:
    ColorVariable:
        enabled: false
    Comment:
        enabled: false
    DeclarationOrder:
        enabled: false
    DuplicateProperty:
        enabled: true
    EmptyLineBetweenBlocks:
        enabled: true
    FinalNewline:
        enabled: true
    IdSelector:
        enabled: false
    Indentation:
        enabled: true
    LeadingZero:
        enabled: true
    NameFormat:
        enabled: false
    NestingDepth:
        enabled: false
    PropertySortOrder:
        enabled: true
    PseudoElement:
        enabled: false
    QualifyingElement:
        enabled: false
    SelectorDepth:
        enabled: false
    SpaceAroundOperator:
        enabled: false
    StringQuotes:
        enabled: true
    VendorPrefix:
        enabled: false
